### ISSUE TITLE
run_look_with_filters.py don't run a Look

### ISSUE THREAD

**Issue by MarioNavarrete** [looker-open-source/sdk-examples#35]
I think the name of this script is not correct.

The file only run the query with filters added manually. Im trying to run a Look with new filters and be able to grab the charts that the Looks has and use this code for that is not useful.
I made small tweaks to the code and I tried this:

```
look_body = sdk.look(look_id)
old_query = look_body.query
request = create_query_request(old_query, filters)
new_query = sdk.create_query(request)
look_body.query = new_query
new_look_response = sdk.update_look(look_id, look_body) 
```

The problem that I am having when running the code appears in the last row that throw  `TypeError: Object of type datetime is not JSON serializable` any idea?

**Comment by josephaxisa** [comment]
Thanks for reaching out, @MarioNavarrete.

The `run_look_with_filters.py` example is intended to run an existing look for which filters are specified at runtime. This means that for a saved look, irrelevant of whether it has filters on it already or not, if for example we want to filter on rows for which `orders.status` is `complete` we invoke `run_look_with_filters.py` like so:

```
$ python run_look_with_filters.py 1 orders.status complete
```
Note that existing filters would be overridden by whatever filters you pass in. If the look was already saved with the desired filters then you should use `sdk.run_look(id, result_format)`. If you want to add to them, the example will have to be slightly modified to create a new query containing both existing and new filters. 

Finally, with regards to the error above, `look_body` is of type `models.LookWithQuery` but `update_look` takes a `body` of type `models.WriteLookWithQuery`. For this reason, during the serialization of `look_body` we encounter a `datetime` type which is only expected in responses and as a result we only have an unstructure hook for it for deserialization purposes. This causes cattrs (the library we use for structuring/unstructuring data) to throw a `TypeError` when it unexpectedly tries to serialize an object with a `datetime` attribute. We will discuss this internally to see if there's a better way to handle such errors.

**Comment by josephaxisa** [comment]
Thanks for reaching out, @MarioNavarrete.

The `run_look_with_filters.py` example is intended to run an existing look for which filters are specified at runtime. This means that for a saved look, irrelevant of whether it has filters on it already or not, if for example we want to filter on rows for which `orders.status` is `complete` we invoke `run_look_with_filters.py` like so:

```
$ python run_look_with_filters.py 1 orders.status complete
```
Note that existing filters would be overridden by whatever filters you pass in. If the look was already saved with the desired filters then you should use `sdk.run_look(id, result_format)`. If you want to add to them, the example will have to be slightly modified to create a new query containing both existing and new filters. 

Finally, with regards to the error above, `look_body` is of type `models.LookWithQuery` but `update_look` takes a `body` of type `models.WriteLookWithQuery`. For this reason, during the serialization of `look_body` we encounter a `datetime` type which is only expected in responses and as a result we only have a structure hook for it for deserialization purposes. This causes cattrs (the library we use for structuring/unstructuring data) to throw a `TypeError` when it unexpectedly tries to serialize an object with a `datetime` attribute. We will discuss this internally to see if there's a better way to handle such errors.
