### ISSUE TITLE
Lookers Swagger.json doesn't work

### ISSUE THREAD

**Issue by mswilson4040** [looker-open-source/sdk-examples#45]
I have been trying to generate an SDK via the provided swagger.json and have had lots of issues with it. I'm not sure if it's specific to C# or Swagger 2.0 vs OpenApi 3.x. But, I've got my suspicions...

We have had some luck with using [Microsoft's AutoRest](https://github.com/Azure/autorest) package to generate a C# Client but it still involves a lot of swagger.json updates. Typically, it's changing something from Snake Case to Camel Case. The downside to using AutoRest is that it is extremely slow and doesn't generate any return Types.

Open Api provides a [generator](https://github.com/OpenAPITools/openapi-generator) that works very quickly and generates types. So we are trying to move to that. Unfortunately, there are still lots of issues. After working my through the a single method (`DashboardAsync` / `GetDashboard`) I noticed that about 99% of all the issues were the result in a type/property in the swagger file not allowing a `null` value

Here's the basic code:

```
var authClient = new ApiAuthApi();
var token = await authClient.LoginAsync("<clientId>, "<clientSecret>");
var config = new Configuration {AccessToken = token._AccessToken};
config.AddDefaultHeader("Authorization", $"token {token._AccessToken}");
            
try
{
    var dashboardApi = new DashboardApi(config);
    var dashes = await dashboardApi.DashboardAsync("<dashboardId>");

    Console.WriteLine(dashes);
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
}
```

The _only_ way I can get this to work is an **extremely** tedious process of updating the swagger.json file. Most of the updates seem are things like:

 - adding `"nullable": true` to any nullable types.
 - Updating `Diction<string, object>` values to have the type of `"object"` instead of `"string"`

But, the interesting part here is that the swagger.json file that Looker gives you is **Swagger 2.0** which doesn't appear (or has some sketchy) support around nullable types. From the docs, it looks like doing something like `"x-nullable": true` is how you would do this. Which, I believe is why we see a lot of `"x-looker-nullable": true` throughout the swagger.json file.

https://github.com/go-swagger/go-swagger/issues/1601

So, since `"x-looker-nullable": true` doesn't work, you're dead in the water. [I found a tool that converts Swagger 2.0 > OpenAPI 3.1](https://mermade.org.uk/openapi-converter) so that I could get `"x-looker-nullable": true` work. It didn't. However, now that the swagger.json file is using OpenAPI 3.1, there _is_ support for `"nullable": true`. AND IT WORKS

**Questions for Looker:**
- What is the official support around the Swagger.json file that is provided directly by looker (found at `https://<your-looker-endpoint>:19999/api/3.0/swagger.json`)
- Why does it not work without **_heavy_** modifications?
- Can Looker provide an updated Swagger file that is up to date (using OpenApi 3.1)?

Here's a couple of relevant discourses:
- https://discourse.looker.com/t/generating-client-sdks-for-the-looker-api/3185/55
- https://discourse.looker.com/t/c-sdk/14892/2

I am happy to provide a Repo of the issue(s) being reproduced if that helps.

**Comment by jkaster** [comment]
If you are on Looker 7.2 or later, I highly recommend using the API 4.0 version of the swagger file. API 4.0 was explicitly started to resolve these issues for strongly typed languages like C#, Kotlin, and Swift. I also recommend using the [legacy option](https://github.com/looker-open-source/sdk-codegen#using-the-legacy-generator) for the SDK Code generator project, and point the `looker.ini` to the API 4.0 version.

I haven't tested the legacy option in a few merges, so feel free to log an issue in `sdk-codegen` if you have a problem with it and I'll look into it.

**Comment by mswilson4040** [comment]
Thanks @jkaster I tried using the 4.0 version and ran into the same issues as 3.1.

The issues coming back are still run time exceptions for trying to parse null values:

> Error converting value {null} to type 'System.Int64'. Path 'refresh_interval_to_i', line 1, position 160.

There is also an issue with file types in the `ApiClient` that prevents the project from building after you generate the client:

> ApiClient.cs(137, 51): [CS1503] Argument 2: cannot convert from 'System.Action<System.IO.Stream>' to 'byte[]'

Code in question:
![image](https://user-images.githubusercontent.com/19480392/76584951-58749d00-649a-11ea-806e-5a24377d1e49.png)

For the **Legacy option**, do you have a little more documentation around that? OpenApi doesn't have any mentioning of the configuration file `lagnuages.ts`. The looker docs also mention `yarn` as the package manager but it's not clear how this `language.ts` file comes into play. I am using NPM but can switch over to yarn if there isn't an npm equivalent.

Do you have a repo of a working c# SDK that's generated from the Looker provided swagger.json file?

**Comment by jkaster** [comment]
- The "legacy" code generator is a [yarn script ](https://github.com/looker-open-source/sdk-codegen/blob/04b7b05ac7dfde446850afcc78c9dc20cac8d4e4/package.json#L19)defined in `packages.json` for the sdk code generator. It uses a script we created to run the OpenAPI generator after fetching the specification from the Looker server configured in the .INI file

- The script is just `ts-node src/legacy.ts` so you could invoke that directly with NPM

- The csharp "legacy" language definition used for `yarn legacy` is at https://github.com/looker-open-source/sdk-codegen/blob/04b7b05ac7dfde446850afcc78c9dc20cac8d4e4/src/languages.ts#L44:L49

- We don't have a repository for the legacy generated C# anywhere, although I believe some customers have used that option successfully. I have not attempted to use the OpenAPI version of a C# API binding myself so I'm not familiar with the problem you're running into. `ApiClient.cs` is an OpenAPI file. What is the Looker API endpoint/SDK method that's calling into ApiClient when it fails?

If you were able to use `yarn legacy` from our project successfully you're currently doing better than me. I just tested and it looks like `yarn legacy` broke again with one of our recent updates. I won't be able to work on that until tomorrow afternoon.

**Comment by mswilson4040** [comment]
Ok, since legacy doesn't work, I'll hold off on that. There actually is a [C# example](https://github.com/looker-open-source/sdk-examples/tree/master/csharp) in this repo, but there's nothing in it. Maybe someone started to create examples for common languages and couldn't get the C# (and others) to work?

It sounds like we have exhausted all options and are back to the original issue that Looker doesn't have a working version of the advertised swagger file.

What is the priority/timeline to get a fix? We rely on the API pretty heavily since our use case is 100% embed and we need the API to make things work.

Is it going to be quicker for us to go through the long, tedious process of fixing everything in the swagger file method by method?

**Comment by jkaster** [comment]
- The empty C# examples folder is currently a place holder for anyone to submit current C# examples. (This repository is for examples only, not for the code generator.)

- Much of what you mention in your initial issue submission is covered in the documentation [sdk-codegen documentation](https://github.com/looker-open-source/sdk-codegen), so I encourage you to review that if you haven't already.

- I have a fix for the `legacy` generator. I'm now working on post-processing of the OpenAPI conversion to switch `x-looker-nullable` to `nullable`. I'll be posting the update to sdk-codegen when that's done, which should be later today.

- We plan to directly publish the OpenAPI version of our API spec right from the Looker server in the future, but that's a major piece of work that hasn't been started yet.

**Comment by jkaster** [comment]
Also, where is `Dictionary<string,object>` incorrect for the API payload? That structure should always have name/value pairs.

**Comment by jkaster** [comment]
https://github.com/looker-open-source/sdk-codegen/pull/187 should resolve the nullable properties issue. Please pull the latest sdk-codegen master and do `yarn legacy` again

**Comment by mswilson4040** [comment]
I pulled down the SDK Repo and ran through the documentation. I tried taking the converted openapi doc and generating a client manually with the openapi generator. In addition, I also tried running the `yarn legacy` generator. Both give you the same results.

The below issues is the sequence of issues I a ran into from plugging in the openapi file, generating a client and trying to use said client to retrieve a Dashboard by Id (`DashboardApi.DashboardAsync`)

**First Issue:**
This issue surfaces immediately when you try and build the project after generating the client:
![image](https://user-images.githubusercontent.com/19480392/76976782-adc50a00-68f1-11ea-8039-06c19d8e7c4a.png)

The current workaround is to just comment that line of code out.

**Second Issue**
When calling `DashboardApi.DashboardAsync`, you get:

> Unexpected character encountered while parsing value: [. Path 'dashboard_elements[0].result_maker.vis_config.y_axes', line 1, position 3071.

This is resolved by changing the `type`of `vis_config.additionalProperties` from `string` to `object` in the `ResultMakerWithIdVisConfigAndDynamicFields` definition in the swagger file

```
          "vis_config": {
            "type": "object",
            "additionalProperties": {
              "type": "object"
            },
            "readOnly": true,
            "description": "Vis config of the constituent Query, or Merge Query.",
            "nullable": true
          }
```

**Third Issue**
After fixing the _Second Issue_, you then run into the next error:

> Unexpected character encountered while parsing value: {. Path 'dashboard_elements[5].query.vis_config.color_application', line 1, position 11978.

This is resolved in a similar way to how I resolved the _Second Issue_

Change `vis_config.additionalProperties` from `string` to `object` and remove the `format` property on the `Query` definition:

```
          "vis_config": {
            "type": "object",
            "additionalProperties": {
              "type": "object"
            },
```

**Fourth Issue**

> Unexpected character encountered while parsing value: [. Path 'dashboard_elements[7].query.filter_config['fact_daily_product_sales.state']', line 1, position 45276.

As you can see, this is a tedious process going through and fixing the swagger file that is provided by Looker. I don't think this issue should be closed since the generator (what the repo is about) does not produce a working swagger file.

It's great that this tool exists because it definitely fixes all the nullable issues we kept hitting. But, there are still quite a bit of issues to resolve. I'm only messing with a single endpoint/method and I've had to change quite a bit, so if you can imagine having to do that for every single endpoint we intend to use, it's a lot of work. Not to mention, if Looker provides a fix or a new version, we would have to go through the entire process of fixing the file again. It's not ideal at all.

Again, I'm more than happy to provide a repository to help with any troubleshooting on your end.

**Comment by dthorpe** [comment]
@mswilson4040 
First, please understand that C# is not yet a language supported by Looker. 

Secondly, the APIs you're starting with are some of the most complex data types in the entire Looker API.  (Congrats! :) )  We've been making adjustments to our metadata to more accurately represent our output, and these changes are why we kicked off the API 4.0 version bump so that we can make structural changes to our types to fix type issues without breaking existing apps using API 3.1. We are aware of a handful of properties in our API which are not strictly typed, whose structure changes depending on use/configuration. vis_config is one of these beasts. From your findings, it sounds like we have some more adjustments to make to vis_config to appease C#. We'll make those adjustments only in the 4.0 API.

We are planning to add support for C# to the Looker SDK codegen project. We're not there yet, but are working toward it. Note also that the "legacy" codegen is not a Looker project, but a separate OSS project, OpenAPI codegen. We created the Looker SDK codegen project largely out of our own frustrations with quality and consistency issues in other solutions.

From our experience bringing Java/Kotlin on board I can assure you that the wonkiness you're seeing with the vis_config property is the exception, not the norm across the rest of the Looker API. 

In the meantime, one workaround you can use right now is to take advantage of the `fields` param on API calls to limit which fields will be returned in the JSON response.  C# won't complain about ambiguities in the vis_config property if your API call says "don't return vis_config in the response." 

I hope this workaround will get you past the vis_config wonkiness and get your Looker integrated app project moving ahead while we work towards producing a complete and Looker-supported C# SDK.

Thanks for your assistance and enthusiasm! I hope we can count on your feedback when we roll out our C# SDK.

Sincerely,
Danny Thorpe
Staff Engineer, Looker Developer Tools Team
(and fulltime C# developer in a past life)

**Comment by mswilson4040** [comment]
@dthorpe 
Thank you, that was exactly what I was wanting clarity on.

> First, please understand that C# is not yet a language supported by Looker.

With that being said, during the development efforts of 4.0, can we work with you on testing it? Long story short, we are tired of having modified swagger.json files scattered across our projects so we are trying to consolidate it all into a Nuget package that we can just import. Much like the current Python offering on pip.

In those efforts, we are trying to move away from Autorest (they don't support return types) and into Open Api Generator. Before we go off modifying the provided looker file, we just want to know the exact reason why we have to do so. You answered that with letting us know that Looker officially doesn't support C#.

I think these two comments sum it up:

> API 4.0 was explicitly started to resolve these issues for strongly typed languages like C#, Kotlin, and Swift.

and of course, the important one:

> First, please understand that C# is not yet a language supported by Looker.

Can we leave this issue open to track progress? I believe the issue is still valid given that c# isn't supported and that it's an issue that (sounds like) it's being actively worked on. I understand if this issue is more appropriate on the https://github.com/looker-open-source/sdk-codegen repo.

**Comment by jkaster** [comment]
A C# SDK is definitely on our roadmap (personally, it's been on my wishlist for a few years). It has become much more feasible with the work we have done on the previous 4 SDKs based on our new code generator. 

It would be great for you to open an issue for a C# SDK in sdk-codegen. We really appreciate your offer to test it, and definitely want your feedback when a prototype is ready. 

I plan to leave this issue closed for this repository because it's not about the SDK examples. Thank you for understanding.
